### ISSUE TITLE
Add  other colliders 

### ISSUE THREAD

**Issue by allan-simon** [kivy-garden/garden.collider#1]
First thanks for this plugin, it works fine and it is really useful 

It would be even better if you could add some other colliders like for example 

```
* Circle / section of circle  
*  Ring / section of ring
* ovoid 
* Common polygon (pentagon, hexagon etc.) 
```

(of course with convenient constructors). Thanks again.

**Comment by akshayaurora** [comment]
@allan-simon please report the issue directly on the repo of garden.collider

**Comment by akshayaurora** [comment]
sry, seems I miss took the issue to be opened on the kivy-garden/garden. Re-opened.

**Comment by matham** [comment]
I've added bezier and circle/ellipse. At the moment I don't have plans to add more shapes so I'm closing for now.

**Comment by allan-simon** [comment]
thanks a lot :)
